<a href="https://colab.research.google.com/github/AmalRam2002/Learn.py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [4]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30', periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie,columns=list('ABCD'))
print("Head:\n",ok.head())
print("\nTail:\n", ok.tail())
print("\nIndex:\n", ok.index)
print("\nColumns:\n", ok.columns)
print("\nValues:\n", ok.values)
print("\nStatistics:\n", ok.describe(include='all'))

Head:
                    A         B         C         D
2021-09-30  0.443912 -0.735615  0.895901  0.135125
2021-10-01 -0.700374 -0.481635 -0.877901 -0.852354
2021-10-02  1.207964 -1.355177  0.600666  0.816203
2021-10-03  1.836868 -0.671395  0.984855 -0.305782

Tail:
                    A         B         C         D
2021-09-30  0.443912 -0.735615  0.895901  0.135125
2021-10-01 -0.700374 -0.481635 -0.877901 -0.852354
2021-10-02  1.207964 -1.355177  0.600666  0.816203
2021-10-03  1.836868 -0.671395  0.984855 -0.305782

Index:
 DatetimeIndex(['2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03'], dtype='datetime64[ns]', freq='D')

Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')

Values:
 [[ 0.44391227 -0.7356152   0.89590075  0.13512531]
 [-0.7003744  -0.48163531 -0.87790114 -0.85235376]
 [ 1.20796374 -1.35517683  0.60066592  0.81620328]
 [ 1.83686823 -0.67139458  0.98485508 -0.30578163]]

Statistics:
               A         B         C         D
count  4.000000  4.000000  4.0

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [5]:
#please provide your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30',periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("\nTranspose\n", ok.transpose())
print("\nDescending Order\n", ok.sort_index(ascending=False))


Transpose
    2021-09-30  2021-10-01  2021-10-02  2021-10-03
A    0.923996    1.479620    0.236518   -1.606297
B   -0.385120    0.697735    0.840020    0.549200
C    0.164334    0.412312    3.172162   -1.274112
D    0.974757    0.246376   -0.161112    0.420807

Descending Order
                    A         B         C         D
2021-10-03 -1.606297  0.549200 -1.274112  0.420807
2021-10-02  0.236518  0.840020  3.172162 -0.161112
2021-10-01  1.479620  0.697735  0.412312  0.246376
2021-09-30  0.923996 -0.385120  0.164334  0.974757
