<a href="https://colab.research.google.com/github/AmalRam2002/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
a =np.random.rand(3,3)
b =np.random.rand(3,3)
print(a)
print(b)

x =np.dot(a,b)
print(x)
x.transpose()


[[0.54590038 0.15060852 0.21395352]
 [0.53285831 0.41484845 0.15295927]
 [0.73467947 0.59107327 0.30101696]]
[[0.16678035 0.2611341  0.68509445]
 [0.00945085 0.02886803 0.31501288]
 [0.40457552 0.30337808 0.3885552 ]]
[[0.17902919 0.21180978 0.5045697 ]
 [0.15467454 0.19752782 0.555174  ]
 [0.24990034 0.30023493 0.80648222]]


array([[0.17902919, 0.15467454, 0.24990034],
       [0.21180978, 0.19752782, 0.30023493],
       [0.5045697 , 0.555174  , 0.80648222]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [3]:
#please provide your answer below this line.
import numpy as np
a =[[55,25,15],[30,44,2],[11,45,77]]
b =np.array(a)
print(b)
np.linalg.det(b)


[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001