<a href="https://colab.research.google.com/github/AmalRam2002/Learn.py/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [5]:
#please type your answer below this line.
import numpy as np
a=np.array([[1,2], [3,4]])
b=np.array([[8],[18]])
np.linalg.solve(a,b)

array([[2.],
       [3.]])

2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [8]:
#please type your answer below this line.
import numpy as np
x=np.array([[2,3,4]])
print(x)
sin_a=np.sin(x)
cos_a=np.cos(x)
tan_a=np.tan(x)
print(sin_a)
print(cos_a)
print(tan_a)

[[2 3 4]]
[[ 0.90929743  0.14112001 -0.7568025 ]]
[[-0.41614684 -0.9899925  -0.65364362]]
[[-2.18503986 -0.14254654  1.15782128]]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [19]:
#please type your answer below this line.
import numpy as np
b=[5,6]
x=2*np.sin(b)
y=2*np.cos(3*b)
z=4*np.tan(2*b)
print(x)
print(y)
print(z)

[-1.91784855 -0.558831  ]
[0.56732437 1.92034057 0.56732437 1.92034057 0.56732437 1.92034057]
[-13.52206002  -1.16402477 -13.52206002  -1.16402477]
