<a href="https://colab.research.google.com/github/AmalRam2002/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [3]:
#please provide your answer below this line.
import numpy as np
a= np.random.rand(3,3)
print(a)


[[0.20212618 0.52676045 0.78147272]
 [0.22144661 0.29026078 0.67646171]
 [0.37833412 0.68497778 0.84704781]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [18]:
#please provide your answer below this line.
import numpy as np
a=np.arange(2,18).reshape(4,4)
b=np.arange(6,22).reshape(4,4)

A=np.vstack(a).reshape(8,2)

B=np.hstack(b).reshape(2,8)

print(A)

print(B)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
[[ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
